### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by LSLeary**
I saw your line in the #xmonad IRC and happen to've been messing around with vector graphics recently (I'm designing a font tailored to writing Haskell), so I had a go. This PR isn't intended to be accepted as is; take a look at the readme and let me know what you think of the options, as well as any ideas you have for tweaking them; I'm not really confident about the colours.

If you decide on a design, I'll remove any extraneous files from the PR and re-render the chosen logo at whatever resolutions you want to use—it'll look better than if you scale the PNG. I can also provide the associated SVG file.

### CODE REVIEW

**Comment by Ongy** [comment]
Thanks. That was quick :)

I like the colourful variant the most.
The idea to integrate a λ is cool.
But at least to me, it looks a bit overloaded and non-obvious when they are both the same colour. I think we can easily grayscale it as well, and keep things obvious.

The two things I would like to test, is to make it a bit taller in proportions (steeper angles).

And while the colours do fit together, I'd like to see if we can get colours that have relation to the project in some way.

The ideas I have in mind:
* [The orange fdo uses for wayland](https://wayland.freedesktop.org/wayland.png)
* [Haskell purple](https://www.haskell.org/static/img/haskell-logo.svg?etag=ukf3Fg7-)
* [XMonad red](https://upload.wikimedia.org/wikipedia/commons/e/e1/Xmonad-logo.svg)

I'm not sure, if we can get two of those fit together well. Maybe the red and orange?

**Comment by LSLeary** [comment]
I'm not clear on what you meant by:
>But at least to me, it looks a bit overloaded and non-obvious when they are both the same colour.

Is this just referring to the first two designs, or do you want the coloured regions chosen differently to how they are in the third design?

The shades of purple from the Haskell logo are a good idea; they've already been well chosen to look good next to one another. The lightest of the three should remain pretty distinct if reduced to grayscale, though either of the other two would be a bit subtle. I don't think the red and orange would go particularly well together, though there's no reason not to try it. Might tweak the shades to see if I can't improve things.

I'll look into a taller version first, and try the colours on that.

**Comment by Ongy** [comment]
I like the regions as they are in the third versions. I was refering to the first two. I took me until I saw the third to "get" the design.

**Comment by HappyEnt** [comment]
What about placing the haskell logo inside waylands? Something like this perhaps
path2985

**Comment by Ongy** [comment]
That's a bit, direct.
And while I like backdrops to/ideas from existing logos, I don't think we should be directly bound to/mixed together from existing ones.

It might be a good fit for hayland though (one of the dependencies I more or less took over for this project).

**Comment by LSLeary** [comment]
OK @ongy, I've made a few changes and tried out some new colours.

 - I realised that rather than being perpendicular, the cutoffs at the top of each stroke should probably be at the same angle as the bottom of the stroke. A comparison is provided in the readme.
 - I made angled strokes steeper, producing a taller W. Comparison provided. I'm not sure it's an improvement, perhaps it would be better to choose a midpoint between this level of steepness and the original, then clip the outside the equals signs so they're not much wider than the W.
 - Speaking of cutting equals signs, I didn't make a comparison but I thought the design might look better with the upper bars of each = stopping just short of the W rather than intersecting, so I tried it. Should look cleaner and clearer like this.
 - A version of the modified design using unaltered Haskell purples is included in the readme.
 - So is a version using the unaltered Wayland orange, and a modified XMonad red—or perhaps more accurately, a red I chose to match the orange. The actual XMonad red is very pure and bright; in thin strokes it goes well enough with the black and grey of the XMonad logo, but not with this orange. I darkened it a bit and pushed it pretty far in the orange direction (maybe too far), but now it fits better.
 - Finally, also included is a demo of another idea I had just now; simply extending what I did with the = to << and >>. It makes it clearer that the logo is made from =<< and >>=, but it's also more disjointed; perhaps not quite as clean? I think I like it anyway.

So I just threw a lot of stuff at the wall, but let me know what you think and we'll narrow it down.

**Comment by Ongy** [comment]
I like the logo4 version.
The purples are nicer for me than the greens (partially because I like dark colours :)
And the red/orange version just doesn't match each other well.

The small gap between the = and the W also looks fine to me.

**Comment by LSLeary** [comment]
@Ongy—round 3:
 - I chopped a little off the outside of the equals signs as I mentioned I might. It's subtle but it should make the whole design feel more square and balanced.
 - More importantly, when I tested rendering at smaller sizes I realised I'd made the strokes too thin. Light strokes are nice and elegant when you have 1000x1000 pixels at hand, but at say 100x100 or lower they're much too vague. I've beefed them up by 25%, looks better now. I included the old thin variants in the readme for direct comparison.

I also made a clean version of the source SVG for direct rendering; it seems to be working fine on the github page so I guess all the PNGs can be deleted. The SVGs are technically able to be rendered at any size but they still have native dimensions—if you want variants that render at specific sizes, let me know. Otherwise I'll just leave the two SVGs that're already in the PR.

Unless there are any tweaks you want, this can be the final design. Let me know and I'll remove anything unnecessary before I rebase/squash.

**Comment by Ongy** [comment]
I feel like the heavy version is a bit too heavy in the big version.
But we could probably keep both and pretend we do HiDPI support and have multiple sizes :)

Oh and clean SVGs are nice. I prefer vectorizes graphics over pixels when it makes sense.
It's easy to generate any size of png from them.

**Comment by LSLeary** [comment]
OK, I cleaned up the PR; there are now just two SVGs added to the repo; a light one and a heavy one. The light set to render at the larger size and the heavy at the smaller.

**Comment by Ongy** [comment]
Cool. Thank you very much

**Pull request merged**
